version: "3"
services:
  bsblookup:
    build: .
    image: newbsblookup
    container_name: bsblookup
    ports:
      - 8080:8080
  blackbox:
    build:
      context: .
      dockerfile: testing/blackbox/Dockerfile
    image: newblackbox
    container_name: blackbox
    depends_on:
      - bsblookup